name: test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: python3 -m pip install --user --upgrade poetry
      - name: install
        run: poetry install
      - name: Run tests
        run: make test
