name: test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade poetry
        run: python3 -m pip install --user --upgrade poetry
      - name: Install dependencies
        run: poetry install
      - name: Run linting
        run: make lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/setup-jsonnet@v10
      - uses: actions/checkout@v2
      - name: install dependencies
        run: python3 -m pip install --user --upgrade poetry
      - name: install
        run: poetry install
      - name: Run tests
        run: make test
